### ISSUE TITLE
Release 1.0.3 Windows doesn't load bookmarks

### ISSUE THREAD

**Issue by yhancik** [webrecorder/webrecorderplayer-electron#26]
When I run **webrecorderplayer-electron-1.0.3.exe** and select an archive to open, it get an empty list ("No bookmarks available in the table" etc).

I noticed that this exe decompresses the actual app folder in %USERPROFILE%\AppData\Local\Temp
Running directly the "**Webrecorder Player.exe**" found there (among [these](https://i.imgpile.com/nn6k71.png)) works as expected.

Disabling the firewall made no difference.

I wonder if it wouldn't make sense to distribute the Windows version as a zipped folder. Running **Webrecorder Player.exe** directly without having **webrecorderplayer-electron-1.0.3.exe** decompress stuff also seems much faster ;)

**Comment by ikreymer** [comment]
We've just released 1.0.6, https://github.com/webrecorder/webrecorderplayer-electron/releases which should at least avoid the firewall prompt.

Perhaps the bookmarks issue is resolved now, although the bookmarks detection is dependent on the WARC containing HTML pages (if its not a Webrecorder WARC). If the WARC does not have HTML pages, there won't be any bookmarks.

As for the packaging, we're using the default Windows distribution with electron: https://www.electron.build/configuration/nsis
I'm not sure that there's a zip option and hesitate to do something custom here..

**Comment by yhancik** [comment]
Hi, thanks for the update! But the issue on my end is still the same.

I don't think the trouble comes from the WARCs, since I can open them properly with the right .exe (and they actually comes from webrecorder.io).

If I run **webrecorderplayer-electron-x86_64-1.0.6.exe**, it unzips this https://imgur.com/IT0ui9M somewhere in Windows' temp folders and launches **Webrecorder Player.exe**. Archives loaded from this instance don't show any content (not even a file size).
I've tried keeping a copy of the temp folder and run it again from there. Same result: not working.

What has worked for me so far is to run **Webrecorder Player.exe** from another location (I realise now I didn't mention that in my first message). Then, the archives content show. 

So I assume the trouble is running **Webrecorder Player.exe** from Windows' temp folders. I'm not familiar enough with Electron, but I see Electron Builder also has a "portable" export. That sounds like a solution to easily run Webrecorder from any location not in temp ;)
https://www.electron.build/
That would also be convenient because the current Windows distribution has to unzip the whole application folder every time (it's deleted from temp when the window is closed), thus much slower to launch.

Is there a way to have the Player output a log to see why it's unable to load an archive when executed from temp?

**Comment by ikreymer** [comment]
Hi, thanks for the additional feedback, this actually helps a lot!

- I made a mistake, we *are* using the `portable` option currently, which produces a self-extracting .exe by default (presumably as this is more portable). However, I do see that there is an  option to create a zip (and other formats). At this point, zip is also quite portable.

- Based on the additional information, I think I've found the problem. Webrecorder Player is using relative paths internally, which is a problem on windows when there are different drives. If the player is run from a different drive than the WARCs are located on, it will have a problem accessing them. Likely your windows temp folder is on one drive, and you are trying to open WARCs that are on another drive. Could you confirm this?

I'll work on a fix for this issue as well, so that WR Player can open WARCs from any drive.

**Comment by yhancik** [comment]
Yes, my system (and therefore temp directory) is on C: but my WARCs were indeed located in E:
Trying to open a WARC from C: loads everything properly! 👍

**Comment by ikreymer** [comment]
Opening WARCs from different drives on Windows should now be working in the latest release (added in 1.0.7)
