### ISSUE TITLE
Player is stuck loading WARC 

### ISSUE THREAD

**Issue by mmejia27** [webrecorder/webrecorderplayer-electron#37]
Using version 1.0.4, loading a relatively small WARC file (7 pages), the player gets stuck in the loading screen. This has happened on both Ubuntu 17.04 and OSX 10.9.

I also seem to have found an easy workaround. While on the loading screen, if you click on the info button in the top right, it will open the info page, but shortly then show the bookmarks for the WARC file and now you are able to view it.

**Comment by ikreymer** [comment]
We just released version 1.0.5, can you check if that is still happening in this version? There have been a number of fixes. If it is, would you be able to send us the WARC so we can test it?
Thanks

**Comment by mmejia27** [comment]
Thanks for following up so quickly. I just tried it with version 1.0.5 and have the same issue, although now the workaround no longer works. I did, however, find a new workaround. Once you load the WARC file, if you click on the logo on the top left, it finishes loading. If you don't click, I left it trying to load for 5 minutes and it still had not completed.

Where can I send the WARC file? It is roughly 11.3MB, so can easily send it over email. I would like to keep the website/WARC file private. @ikreymer

**Comment by ikreymer** [comment]
Sure, can you send it the WARC to us at support [at] webrecorder.io ? Or, if you could upload it somewhere and us a private download link, that would work as well. We'll try to resolve the issue for next release. Thanks.

**Comment by mmejia27** [comment]
I've gone ahead and emailed it to you at that address. Thanks!

**Comment by atomotic** [comment]
i opened the file you've sent and it's working.

would you check if there is a stale process `webrecorder` running on your machine, even if the player has been closed?  you can use in your shell:

    pgrep webrecorder

if something is returned, then kill it and reopen the warc with the player:

   pkill webrecorder

**Comment by mmejia27** [comment]
@atomotic I did not see any stale processes for webrecorder.

**Comment by wsampson** [comment]
I am also having this problem on 1.05 and didn't detect any stale processes. WARC is ~5 MB.

**Comment by wsampson** [comment]
@ikreymer I'm running it on OS X

**Comment by ikreymer** [comment]
Oops, didn't mean to close this.. We've just released: https://github.com/webrecorder/webrecorderplayer-electron/releases/tag/v1.0.6
There were some improvements to the loading process and I think this issue should be fixed..
can you double check @mmejia27 @wsampson if it works better now?

**Comment by mmejia27** [comment]
@ikreymer Looks like adding that timeout on load solves the issue for me! Thanks!

**Comment by wsampson** [comment]
@ikreymer I'm still getting an infinite load time for very small collections/WARCs on macOS

**Comment by cbogart** [comment]
I have the same problem; I've tried both 1.0.8 and 1.1.1, on OSX 10.11.6.  I tried opening both a .warc file and a .warc.gz file, but all that happens is a spinning arrow animation.  My warc file has five pages and is 1.9 MB.

**Comment by m4rk3r** [comment]
@cbogart would you be willing to try [this new build](https://s3.amazonaws.com/webrecorder-builds/electron-player/beta-1.1.2/webrecorder-player-1.1.2.dmg) that includes some extra diagnostic info? 

After loading a WARC, if you get the infinite spinner, could you open the help page (`i` top right corner) and scroll down to the bottom and expand the "Additional Debug Info" and email us any extra info in that section at support@webrecorder.io?

**Comment by cbogart** [comment]
Sure.  It just says "No additional info".  Then when I hit the X to get out of the help screen, the spinner is gone and the "LOAD web archive" button has returned.

**Comment by m4rk3r** [comment]
@cbogart Ok, thanks for trying that!

**Comment by ikreymer** [comment]
We think this is an issue with building on newer version of OSX, per: pyinstaller/pyinstaller#1191.

The default build is on 10.12.6 (https://docs.travis-ci.com/user/reference/osx/#OS-X-Version) but TravisCI supports down to 10.10. Hopefully that will work and then we can support >=10.10

**Comment by ikreymer** [comment]
1.0.9 and 1.1.2 now released! Both should run in OSX >= 10.10
(OSX 10.9 and older are not supported).

**Comment by nar001** [comment]
Hello so it still happens for me apparently, I try to load a big archive and it just stalls at 100% ("Oops, seems like indexing has stalled" or such) and in additional info I have :
"Created user local with the email test@localhost and the role: 'public-archivist' 
WARCSERVER_HOST=http://localhost:53706 

APP_HOST=http://localhost:53707 "

I'm not sure what the problem is. Thanks!

**Comment by m4rk3r** [comment]
Hi @nar001, how big is the warc you are attempting to load? Right now the player has a rough limit of around 5 GB.

**Comment by nar001** [comment]
Roughly 1gb or so, I have another that's 12GB actually so it'd make sense why that one wouldn't load. Actually, why 5GB as a limit?

**Comment by m4rk3r** [comment]
It's not a hard limit, but generally where things tend to bog down. We'll be supporting bigger warcs in the near future.

**Comment by FrankEBailey** [comment]
I'm trying to open a 50 gig file and it goes all the way to 100% and then says indexing is stalled. The service starts and I can navigate to the interface in my browser, but it just says "almost done" and never gets further.

**Comment by MadRatSRP** [comment]
Same to me
